name: real_time_chart
description: A Flutter package for displaying real-time charts with flexible customization options.
version: 0.0.1
homepage: https://github.com/tajaouart/real_time_chart

environment:
  sdk: '>=2.19.2 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
